spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: JB9syjMTBvO3ukLHSdtG
            client-secret: elk2g6dS9q
          kakao:
            clientId: 024e1da8176dcc81873b4e4211ba00e1
            client-secret: 47f7393c492f9d11a94d4ebc612c04af
          google:
            clientId: 467427588324-sscot9sdqc4en9slsfg5b5vsmpt0tu2c.apps.googleusercontent.com
            client-secret: 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
          facebook:
            clientId: 163701019689097
            client-secret: 861e97055b88567c292138fc6b3b5b26
          instagram:
            clientId: 785899026437950
            client-secret: 1423e49c6f9b202dcf6beb2d75330006