spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: JB9syjMTBvO3ukLHSdtG
            client-secret: bF728NkjMV
          kakao:
            clientId: 024e1da8176dcc81873b4e4211ba00e1
            client-secret: NJ8AGmcMVlOTxVNIWoGMrJyVqEj46gJJ
          google:
            clientId: 467427588324-sscot9sdqc4en9slsfg5b5vsmpt0tu2c.apps.googleusercontent.com
            client-secret: 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
          facebook:
            clientId: 'CLIENT ID'
            client-secret: 'CLIENT PASSWORD'
          instagram:
            clientId: 'CLIENT ID'
            client-secret: 'CLIENT PASSWORD'